server:
  port: 8081

spring:
  application:
    name: inventory-service
  config:
    import: "optional:configserver:http://config-server:8888"
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,refresh
  endpoint:
    health:
      show-details: always
